@tool
extends RefCounted

# Generated by addons/fmod_player/tools/generate_property_translations.gd.
# Edit fmod_property_translations.csv, then rerun the generator.

const LOCALES := ["zh_Hans", "zh_Hant", "ja", "ru"]
const MESSAGES := {
	"Fmod": {
		"zh_Hans": "FMOD",
		"zh_Hant": "FMOD",
		"ja": "FMOD",
		"ru": "FMOD",
	},
	"3d": {
		"zh_Hans": "3D",
		"zh_Hant": "3D",
		"ja": "3D",
		"ru": "3D",
	},
	"Init Flags": {
		"zh_Hans": "初始化标志",
		"zh_Hant": "初始化標誌",
		"ja": "初期化フラグ",
		"ru": "Флаги инициализации",
	},
	"Show Startup Banner": {
		"zh_Hans": "显示启动横幅",
		"zh_Hant": "顯示啟動橫幅",
		"ja": "スタートアップバナーを表示",
		"ru": "Показать стартовый баннер",
	},
	"Max Channels": {
		"zh_Hans": "最大通道数",
		"zh_Hant": "最大通道數",
		"ja": "最大チャンネル数",
		"ru": "Макс. каналов",
	},
	"Software Channels": {
		"zh_Hans": "软件通道数",
		"zh_Hant": "軟體通道數",
		"ja": "ソフトウェアチャンネル数",
		"ru": "Программные каналы",
	},
	"Output Type": {
		"zh_Hans": "输出类型",
		"zh_Hant": "輸出類型",
		"ja": "出力タイプ",
		"ru": "Тип выхода",
	},
	"Software Sample Rate": {
		"zh_Hans": "软件采样率",
		"zh_Hant": "軟體取樣率",
		"ja": "ソフトウェアサンプリングレート",
		"ru": "Программная частота дискретизации",
	},
	"Speaker Mode": {
		"zh_Hans": "扬声器模式",
		"zh_Hant": "揚聲器模式",
		"ja": "スピーカーモード",
		"ru": "Режим динамиков",
	},
	"Num Raw Speakers": {
		"zh_Hans": "原始扬声器数量",
		"zh_Hant": "原始揚聲器數量",
		"ja": "生スピーカー数",
		"ru": "Количество исходных динамиков",
	},
	"Dsp Buffer Size": {
		"zh_Hans": "DSP 缓冲区大小",
		"zh_Hant": "DSP 緩衝區大小",
		"ja": "DSP バッファサイズ",
		"ru": "Размер DSP-буфера",
	},
	"Dsp Buffer Count": {
		"zh_Hans": "DSP 缓冲区数量",
		"zh_Hant": "DSP 緩衝區數量",
		"ja": "DSP バッファ数",
		"ru": "Количество DSP-буферов",
	},
	"Stream Buffer Size": {
		"zh_Hans": "流缓冲区大小",
		"zh_Hant": "流緩衝區大小",
		"ja": "ストリームバッファサイズ",
		"ru": "Размер потокового буфера",
	},
	"Stream From Update": {
		"zh_Hans": "在更新线程中流式读取",
		"zh_Hant": "在更新線程中流式讀取",
		"ja": "アップデートからストリーム",
		"ru": "Поток из обновления",
	},
	"Mix From Update": {
		"zh_Hans": "在更新线程中混音",
		"zh_Hant": "在更新線程中混音",
		"ja": "アップデートからミックス",
		"ru": "Микширование из обновления",
	},
	"3d Right Handed": {
		"zh_Hans": "3D 右手坐标系",
		"zh_Hant": "3D 右手坐標系",
		"ja": "3D 右手座標系",
		"ru": "3D правая система координат",
	},
	"Clip Output": {
		"zh_Hans": "裁剪输出",
		"zh_Hant": "裁剪輸出",
		"ja": "クリップ出力",
		"ru": "Обрезка выхода",
	},
	"Channel Low-pass": {
		"zh_Hans": "通道低通",
		"zh_Hant": "通道低通",
		"ja": "チャンネルローパス",
		"ru": "Низкочастотный фильтр канала",
	},
	"Channel Distance Filter": {
		"zh_Hans": "通道距离滤波",
		"zh_Hant": "通道距離濾波",
		"ja": "チャンネル距離フィルタ",
		"ru": "Фильтр дистанции канала",
	},
	"Vol 0 Becomes Virtual": {
		"zh_Hans": "音量为零时虚拟化",
		"zh_Hant": "音量為零時虛擬化",
		"ja": "音量0で仮想化",
		"ru": "Громкость 0 становится виртуальной",
	},
	"Geometry Use Closest": {
		"zh_Hans": "几何体使用最近面",
		"zh_Hant": "幾何體使用最近面",
		"ja": "ジオメトリ最近面使用",
		"ru": "Геометрия: ближайшая поверхность",
	},
	"Prefer Dolby Downmix": {
		"zh_Hans": "优先 Dolby 下混",
		"zh_Hant": "優先 Dolby 下混",
		"ja": "Dolby ダウンミックス優先",
		"ru": "Предпочтительный Dolby Downmix",
	},
	"Thread Unsafe": {
		"zh_Hans": "非线程安全",
		"zh_Hant": "非執行緒安全",
		"ja": "スレッド非安全",
		"ru": "Непотокобезопасно",
	},
	"Profile Meter All": {
		"zh_Hans": "统计全部 Profile 指标",
		"zh_Hant": "統計全部 Profile 指標",
		"ja": "全プロファイルメーター",
		"ru": "Измерить все профили",
	},
	"Memory Tracking": {
		"zh_Hans": "内存跟踪",
		"zh_Hant": "記憶體追蹤",
		"ja": "メモリトラッキング",
		"ru": "Отслеживание памяти",
	},
	"Enable Profile": {
		"zh_Hans": "启用 Profile",
		"zh_Hant": "啟用 Profile",
		"ja": "プロファイルを有効化",
		"ru": "Включить профилирование",
	},
	"Profile Port": {
		"zh_Hans": "Profile 端口",
		"zh_Hant": "Profile 端口",
		"ja": "プロファイルポート",
		"ru": "Порт профилирования",
	},
	"Network Proxy": {
		"zh_Hans": "网络代理",
		"zh_Hant": "網絡代理",
		"ja": "ネットワークプロキシ",
		"ru": "Сетевой прокси",
	},
	"Network Timeout": {
		"zh_Hans": "网络超时",
		"zh_Hant": "網絡超時",
		"ja": "ネットワークタイムアウト",
		"ru": "Сетевой таймаут",
	},
	"Doppler Scale": {
		"zh_Hans": "多普勒缩放",
		"zh_Hant": "多普勒縮放",
		"ja": "ドップラースケール",
		"ru": "Масштаб Доплера",
	},
	"Distance Factor": {
		"zh_Hans": "距离系数",
		"zh_Hant": "距離係數",
		"ja": "距離係数",
		"ru": "Фактор расстояния",
	},
	"Rolloff Scale": {
		"zh_Hans": "衰减缩放",
		"zh_Hant": "衰減縮放",
		"ja": "ロールオフスケール",
		"ru": "Масштаб затухания",
	},
	"Num Listeners": {
		"zh_Hans": "监听器数量",
		"zh_Hant": "監聽器數量",
		"ja": "リスナー数",
		"ru": "Количество слушателей",
	},
	"Geometry Max Fade Time": {
		"zh_Hans": "几何遮挡最大淡化时间",
		"zh_Hant": "幾何遮擋最大淡化時間",
		"ja": "ジオメトリ最大フェード時間",
		"ru": "Макс. время затухания геометрии",
	},
	"Distance Filter Center Freq": {
		"zh_Hans": "距离滤波中心频率",
		"zh_Hant": "距離濾波中心頻率",
		"ja": "距離フィルタ中心周波数",
		"ru": "Центральная частота фильтра дистанции",
	},
	"Default Decode Buffer Size": {
		"zh_Hans": "默认解码缓冲区大小",
		"zh_Hant": "默認解碼緩衝區大小",
		"ja": "デフォルトデコードバッファサイズ",
		"ru": "Размер буфера декодирования по умолчанию",
	},
	"Dsp Buffer Pool Size": {
		"zh_Hans": "DSP 缓冲池大小",
		"zh_Hant": "DSP 緩衝池大小",
		"ja": "DSP バッファプールサイズ",
		"ru": "Размер пула DSP-буферов",
	},
	"Resampler Method": {
		"zh_Hans": "重采样方法",
		"zh_Hant": "重採樣方法",
		"ja": "リサンプリング方式",
		"ru": "Метод ресемплинга",
	},
	"Random Seed": {
		"zh_Hans": "随机种子",
		"zh_Hant": "隨機種子",
		"ja": "ランダムシード",
		"ru": "Случайное зерно",
	},
	"Max Convolution Threads": {
		"zh_Hans": "最大卷积线程数",
		"zh_Hant": "最大卷積線程數",
		"ja": "最大畳み込みスレッド数",
		"ru": "Макс. потоков свёртки",
	},
	"Max Spatial Objects": {
		"zh_Hans": "最大空间对象数",
		"zh_Hant": "最大空間對象數",
		"ja": "最大空間オブジェクト数",
		"ru": "Макс. пространственных объектов",
	},
	"Vol 0 Virtual Vol": {
		"zh_Hans": "音量为零时虚拟音量",
		"zh_Hant": "音量為零時虛擬音量",
		"ja": "音量0仮想音量",
		"ru": "Виртуальная громкость при громкости 0",
	},
	"Max Mpeg Codecs": {
		"zh_Hans": "最大 MPEG 解码器数",
		"zh_Hant": "最大 MPEG 解碼器數",
		"ja": "最大 MPEG コーデック数",
		"ru": "Макс. MPEG-кодеков",
	},
	"Max Adpcm Codecs": {
		"zh_Hans": "最大 ADPCM 解码器数",
		"zh_Hant": "最大 ADPCM 解碼器數",
		"ja": "最大 ADPCM コーデック数",
		"ru": "Макс. ADPCM-кодеков",
	},
	"Max Xma Codecs": {
		"zh_Hans": "最大 XMA 解码器数",
		"zh_Hant": "最大 XMA 解碼器數",
		"ja": "最大 XMA コーデック数",
		"ru": "Макс. XMA-кодеков",
	},
	"Max Vorbis Codecs": {
		"zh_Hans": "最大 Vorbis 解码器数",
		"zh_Hant": "最大 Vorbis 解碼器數",
		"ja": "最大 Vorbis コーデック数",
		"ru": "Макс. Vorbis-кодеков",
	},
	"Max At 9 Codecs": {
		"zh_Hans": "最大 AT9 解码器数",
		"zh_Hant": "最大 AT9 解碼器數",
		"ja": "最大 AT9 コーデック数",
		"ru": "Макс. AT9-кодеков",
	},
	"Max Fadpcm Codecs": {
		"zh_Hans": "最大 FADPCM 解码器数",
		"zh_Hant": "最大 FADPCM 解碼器數",
		"ja": "最大 FADPCM コーデック数",
		"ru": "Макс. FADPCM-кодеков",
	},
	"Max Opus Codecs": {
		"zh_Hans": "最大 Opus 解码器数",
		"zh_Hant": "最大 Opus 解碼器數",
		"ja": "最大 Opus コーデック数",
		"ru": "Макс. Opus-кодеков",
	},
	"Suggested Sound Type": {
		"zh_Hans": "建议的声音类型",
		"zh_Hant": "建議的聲音類型",
		"ja": "推奨サウンドタイプ",
		"ru": "Рекомендуемый тип звука",
	},
	"Length Override": {
		"zh_Hans": "长度覆盖",
		"zh_Hant": "長度覆蓋",
		"ja": "長さオーバーライド",
		"ru": "Переопределение длины",
	},
	"File Offset": {
		"zh_Hans": "文件偏移",
		"zh_Hant": "檔案偏移",
		"ja": "ファイルオフセット",
		"ru": "Смещение файла",
	},
	"Decode Buffer Size": {
		"zh_Hans": "解码缓冲区大小",
		"zh_Hant": "解碼緩衝區大小",
		"ja": "デコードバッファサイズ",
		"ru": "Размер буфера декодирования",
	},
	"Initial Subsound": {
		"zh_Hans": "初始子声音",
		"zh_Hant": "初始子聲音",
		"ja": "初期サブサウンド",
		"ru": "Начальный подзвук",
	},
	"Num Subsounds": {
		"zh_Hans": "子声音数量",
		"zh_Hant": "子聲音數量",
		"ja": "サブサウンド数",
		"ru": "Количество подзвуков",
	},
	"Inclusion List": {
		"zh_Hans": "包含列表",
		"zh_Hant": "包含列表",
		"ja": "インクルージョンリスト",
		"ru": "Список включений",
	},
	"Dls Name": {
		"zh_Hans": "DLS 名称",
		"zh_Hant": "DLS 名稱",
		"ja": "DLS 名",
		"ru": "Имя DLS",
	},
	"Encryption Key": {
		"zh_Hans": "加密密钥",
		"zh_Hant": "加密密鑰",
		"ja": "暗号化キー",
		"ru": "Ключ шифрования",
	},
	"Initial Seek Position": {
		"zh_Hans": "初始寻道",
		"zh_Hant": "初始尋道",
		"ja": "初期シーク位置",
		"ru": "Начальная позиция поиска",
	},
	"Ignore Set File System": {
		"zh_Hans": "忽略设置文件系统",
		"zh_Hant": "忽略設定檔案系統",
		"ja": "ファイルシステム設定を無視",
		"ru": "Игнорировать установленную файловую систему",
	},
}

static func create_translations() -> Array[Translation]:
	var translations: Array[Translation] = []
	for locale: String in LOCALES:
		var translation: Translation = Translation.new()
		translation.locale = locale
		for source: String in MESSAGES:
			var value: String = String(MESSAGES[source].get(locale, ""))
			if value.is_empty():
				continue
			translation.add_message(StringName(source), StringName(value))
		translations.append(translation)
	return translations
