@tool
extends RefCounted

const DEFAULT_CSV_PATH: String = "res://addons/fmod_player/translations/fmod_property_translations.csv"
const DEFAULT_OUTPUT_PATH: String = "res://addons/fmod_player/translations/fmod_property_translations.gd"

static func generate(csv_path: String = DEFAULT_CSV_PATH, output_path: String = DEFAULT_OUTPUT_PATH, verbose: bool = true) -> bool:
	var data: Dictionary = _read_translation_csv(csv_path)
	if data.is_empty():
		return false

	var script_text: String = _generate_translation_script(data["locales"], data["messages"])
	if not _write_text(output_path, script_text):
		return false

	if verbose:
		print("Generated FMOD property translations")
		print("  CSV: %s" % _to_absolute_path(csv_path))
		print("  Output: %s" % _to_absolute_path(output_path))
	return true

static func _write_translation_csv(path: String, data: Dictionary) -> void:
	var locales: PackedStringArray = data.get("locales", PackedStringArray())
	var messages: Array[Dictionary] = data.get("messages", [])
	
	var file: FileAccess = FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		push_error("Cannot write CSV: %s" % FileAccess.get_open_error())
		return
	
	var header: PackedStringArray = PackedStringArray(["source"])
	header.append_array(locales)
	file.store_csv_line(header)
	
	for message: Dictionary in messages:
		var row: PackedStringArray = PackedStringArray([message.get("source", "")])
		var translations: Dictionary = message.get("translations", {})
		for locale: String in locales:
			row.append(translations.get(locale, ""))
		file.store_csv_line(row)
	
	file.close()

static func _read_translation_csv(path: String) -> Dictionary:
	var absolute_path := _to_absolute_path(path)
	var file: FileAccess = FileAccess.open(absolute_path, FileAccess.READ)
	if not file:
		push_error("Unable to open CSV: %s" % absolute_path)
		return Dictionary()

	var header := file.get_csv_line()
	if header.size() < 2 or header[0].strip_edges() != "source":
		push_error("CSV header must start with source and at least one locale column.")
		return Dictionary()

	var locales: Array[String] = []
	var seen_locales: Dictionary
	for index in range(1, header.size()):
		var locale: String = header[index].strip_edges()
		if not locale.is_empty():
			if seen_locales.has(locale):
				push_error("Duplicate locale column in CSV: %s" % locale)
				return Dictionary()
			seen_locales[locale] = true
			locales.append(locale)

	if locales.is_empty():
		push_error("CSV must contain at least one locale column.")
		return Dictionary()

	var messages: Array[Dictionary] = []
	var seen_sources: Dictionary
	while not file.eof_reached():
		var row: PackedStringArray = file.get_csv_line()
		if row.is_empty() or _is_blank_row(row):
			continue

		var source: String = row[0].strip_edges()
		if source.is_empty() or source.begins_with("#"):
			continue

		if seen_sources.has(source):
			push_error("Duplicate source in CSV: %s" % source)
			return Dictionary()
		seen_sources[source] = true

		var translations: Dictionary
		for locale_index in range(locales.size()):
			var value_index := locale_index + 1
			if value_index >= row.size():
				continue

			var value: String = row[value_index]
			if not value.is_empty():
				translations[locales[locale_index]] = value

		if not translations.is_empty():
			messages.append({
				"source": source,
				"translations": translations,
			})

	return {
		"locales": locales,
		"messages": messages,
	}

static func _is_blank_row(row: PackedStringArray) -> bool:
	for value: String in row:
		if not value.strip_edges().is_empty():
			return false
	return true

static func _generate_translation_script(locales: Array[String], messages: Array[Dictionary]) -> String:
	var lines: Array[String] = [
		"@tool",
		"extends RefCounted",
		"",
		"# Generated by addons/fmod_player/tools/generate_property_translations.gd.",
		"# Edit fmod_property_translations.csv, then rerun the generator.",
		"",
		"const LOCALES := %s" % _gd_array(locales),
		"const MESSAGES := {",
	]

	for message: Dictionary in messages:
		var source: String = String(message["source"])
		var translations: Dictionary = message["translations"] as Dictionary
		lines.append("\t%s: {" % _gd_string(source))
		for locale: String in locales:
			if not translations.has(locale):
				continue
			lines.append("\t\t%s: %s," % [_gd_string(locale), _gd_string(translations[locale])])
		lines.append("\t},")

	lines.append_array([
		"}",
		"",
		"static func create_translations() -> Array[Translation]:",
		"\tvar translations: Array[Translation] = []",
		"\tfor locale: String in LOCALES:",
		"\t\tvar translation: Translation = Translation.new()",
		"\t\ttranslation.locale = locale",
		"\t\tfor source: String in MESSAGES:",
		"\t\t\tvar value: String = String(MESSAGES[source].get(locale, \"\"))",
		"\t\t\tif value.is_empty():",
		"\t\t\t\tcontinue",
		"\t\t\ttranslation.add_message(StringName(source), StringName(value))",
		"\t\ttranslations.append(translation)",
		"\treturn translations",
		"",
	])

	return "\n".join(lines)

static func _gd_array(values: Array[String]) -> String:
	var result: Array[String] = []
	for value in values:
		result.append(_gd_string(value))
	return "[%s]" % ", ".join(result)

static func _gd_string(value: String) -> String:
	return "\"%s\"" % value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")

static func _write_text(path: String, text: String) -> bool:
	var absolute_path: String = _to_absolute_path(path)
	var directory: String = absolute_path.get_base_dir()
	if DirAccess.make_dir_recursive_absolute(directory) != OK:
		push_error("Unable to create output directory: %s" % directory)
		return false

	var file: FileAccess = FileAccess.open(absolute_path, FileAccess.WRITE)
	if not file:
		push_error("Unable to write output: %s" % absolute_path)
		return false

	file.store_string(text)
	return true

static func _to_absolute_path(path: String) -> String:
	if path.begins_with("res://") or path.begins_with("user://"):
		return ProjectSettings.globalize_path(path)
	return path
